import { GameProduct } from './types';

export const INITIAL_PRODUCTS: GameProduct[] = [
  // Robux
  {
    id: 'robux-gp-1',
    category: 'Robux',
    name: '1,000 Robux (System Gamepass)',
    description: 'Instan via Roblox Gamepass. Bot kami akan membeli Gamepass Anda secara otomatis dalam hitungan detik setelah pembayaran dikonfirmasi.',
    price: 115000,
    originalPrice: 135000,
    stock: 8450,
    deliveryType: 'Instant Gamepass',
    imagePlaceholder: 'emerald-gradient',
    badge: 'Paling Populer',
    vipPriceDiscount: 5, // 5% additional discount
  },
  {
    id: 'robux-gf-2',
    category: 'Robux',
    name: '5,000 Robux (Group Funds - Fast)',
    description: 'Robux dikirim langsung melalui dana grup Roblox. Memerlukan akun Anda masuk ke grup kami (disediakan tautan otomatis).',
    price: 549000,
    originalPrice: 599000,
    stock: 1200,
    deliveryType: 'Group Funds',
    imagePlaceholder: 'blue-gradient',
    vipPriceDiscount: 4,
  },
  
  // Fisch Items
  {
    id: 'fisch-rod-abyssal',
    category: 'Fisch',
    name: 'Abyssal Rod [Legendary]',
    description: 'Joran pancing mitis terkuat di map Fisch Roblox. Memberikan bonus keberuntungan +250% dan ketahanan tangkapan laut dalam.',
    price: 49000,
    originalPrice: 75000,
    stock: 85,
    deliveryType: 'Secure Trading Server',
    imagePlaceholder: 'purple-gold-gradient',
    badge: 'Terlaris Fisch',
    vipPriceDiscount: 8, // 8% discount for Premium
  },
  {
    id: 'fisch-rod-auroral',
    category: 'Fisch',
    name: 'Auroral Rod [Divine]',
    description: 'Memancarkan aura Aurora Borealis di dalam game. Kesempatan menangkap ikan Mutated meningkat 3x lipat.',
    price: 79000,
    originalPrice: 110000,
    stock: 30,
    deliveryType: 'Secure Trading Server',
    imagePlaceholder: 'nebula-gradient',
    vipPriceDiscount: 10,
  },
  {
    id: 'fisch-secret-megalodon',
    category: 'Fisch',
    name: 'Ikan Secret: Prehistoric Megalodon',
    description: 'Ikan rahasia purba berkuran kolosal yang sangat langka. Memiliki harga jual in-game fantastis dan efek pamer bergengsi tinggi!',
    price: 85000,
    originalPrice: 130000,
    stock: 12,
    deliveryType: 'Secure Trading Server',
    imagePlaceholder: 'deep-blue-gradient',
    badge: 'Ikan Secret Terlangka',
    vipPriceDiscount: 12,
  },
  {
    id: 'fisch-secret-neon-whisper',
    category: 'Fisch',
    name: 'Ikan Secret: Golden Whisper',
    description: 'Spesies ikan gaib berbalut partikel emas mistis. Hanya muncul saat kondisi khusus badai es malam hari.',
    price: 69000,
    originalPrice: 95000,
    stock: 25,
    deliveryType: 'Secure Trading Server',
    imagePlaceholder: 'gold-shimmer-gradient',
    badge: 'Limited Secret',
    vipPriceDiscount: 10,
  },
  {
    id: 'fisch-skin-neon-matrix',
    category: 'Fisch',
    name: 'Rod Skin: Golden Neon Matrix',
    description: 'Skin joran premium bercahaya hologram neon cyberpunk mengalir. Memberikan kustomisasi visual memukau saat digunakan memancing.',
    price: 25000,
    originalPrice: 35000,
    stock: 150,
    deliveryType: 'Automatic Bot',
    imagePlaceholder: 'yellow-leopard-gradient',
    badge: 'Skin Rod Baru',
    vipPriceDiscount: 5,
  },
  {
    id: 'fisch-skin-cosmic-shadder',
    category: 'Fisch',
    name: 'Rod Skin: Cosmic Nebula Animated',
    description: 'Kosmetik joran pancing animasi shader awan interstellar bergerak. Bergerak interaktif mengikuti ayunan pancing Anda.',
    price: 34500,
    originalPrice: 45000,
    stock: 80,
    deliveryType: 'Automatic Bot',
    imagePlaceholder: 'nebula-gradient',
    badge: 'Fisch Skin Terpopuler',
    vipPriceDiscount: 7,
  },
  {
    id: 'fisch-coins-10k-pack',
    category: 'Fisch',
    name: 'Top Up: 10,000 Fisch Gold Coins',
    description: 'Top up instan koin emas Fisch in-game Anda. Saldo langsung disalurkan dari akun penampungan bot trading autopilot kami.',
    price: 15000,
    originalPrice: 20000,
    stock: 500,
    deliveryType: 'Automatic Bot',
    imagePlaceholder: 'emerald-gradient',
    badge: 'Instant Delivery',
    vipPriceDiscount: 5,
  },
  {
    id: 'fisch-coins-50k-mega',
    category: 'Fisch',
    name: 'Top Up: 50,000 Fisch Gold Coins [Mega Pack]',
    description: 'Paket koin emas Fisch dalam jumlah besar untuk percepatan gacha umpan dan upgrade ketahanan tali pancing.',
    price: 64000,
    originalPrice: 85000,
    stock: 240,
    deliveryType: 'Automatic Bot',
    imagePlaceholder: 'light-violet-gradient',
    badge: 'Best Value Coin',
    vipPriceDiscount: 8,
  },
  {
    id: 'fisch-bait-golden',
    category: 'Fisch',
    name: '50x Golden Bait Bundle',
    description: 'Paket umpan emas legendaris. Otomatis ditaruh di akun Anda melalui bot trading VIP di private server.',
    price: 19500,
    originalPrice: 30000,
    stock: 400,
    deliveryType: 'Automatic Bot',
    imagePlaceholder: 'gold-gradient',
    vipPriceDiscount: 5,
  },

  // Blox Fruits Items
  {
    id: 'bf-fruit-kitsune',
    category: 'Blox Fruits',
    name: 'Kitsune Fruit [Permanent]',
    description: 'Buah iblis permanen Kitsune, buah tier SSS paling dicari. Kami mengirimkan via gift instan di private server buatan bot.',
    price: 249000,
    originalPrice: 299000,
    stock: 14,
    deliveryType: 'Secure Trading Server',
    badge: 'Hot Item',
    imagePlaceholder: 'red-fire-gradient',
    vipPriceDiscount: 6,
  },
  {
    id: 'bf-fruit-leopard',
    category: 'Blox Fruits',
    name: 'Leopard Fruit [Physical Trading]',
    description: 'Physical item buah Leopard untuk di-trade langsung di Cafe server kedua (Sea 2) secara aman dan langsung dipandu bot.',
    price: 35000,
    originalPrice: 50000,
    stock: 120,
    deliveryType: 'Secure Trading Server',
    imagePlaceholder: 'yellow-leopard-gradient',
    vipPriceDiscount: 5,
  },

  // Pet Simulator X / 99
  {
    id: 'ps99-titanic-cat',
    category: 'Pet Simulator X',
    name: 'Titanic Cat Pet',
    description: 'Pet berukuran raksasa Titanic dengan statistik super OP. Pengiriman super aman via In-Game Mailbox atau Trade Plaza.',
    price: 185000,
    originalPrice: 220000,
    stock: 8,
    deliveryType: 'Automatic Bot',
    imagePlaceholder: 'light-violet-gradient',
    badge: 'Limited Stock',
    vipPriceDiscount: 7,
  }
];

export const PAYMENT_METHODS = [
  { id: 'qris', name: 'QRIS (Gopay/Dana/Ovo/LinkAja)', type: 'E-Wallet', logo: '📱', adminFee: 1000 },
  { id: 'gopay-auto', name: 'GoPay Auto-Pay (Mendukung Langganan Recurring)', type: 'Direct Wallet', logo: '🟢', adminFee: 1500 },
  { id: 'shopeepay', name: 'ShopeePay', type: 'E-Wallet', logo: '🟠', adminFee: 1500 },
  { id: 'mandiri-va', name: 'Mandiri Virtual Account', type: 'VA Bank', logo: '🏛️', adminFee: 2500 },
  { id: 'bca-va', name: 'BCA Virtual Account', type: 'VA Bank', logo: '🏛️', adminFee: 2500 },
];
